baseURL = "https://bkkavin.github.io/"
languageCode = "en-us"
title = "B K Kavin"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
relativeURL = true

[params]
  description = "B K Kavin's Blog"
  copyright = "Copyright © 2020 B K Kavin"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    identifier = "blog"
    name = "μblog"
    title = "blog"
    url = "/blog/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
