#! /bin/bash
cp ~/git/dotfiles/.bashrc ~
cp ~/git/dotfiles/init.el ~/.emacs.d/ 
cp ~/git/dotfiles/init_bkk.org ~/.emacs.d/ 
cp ~/git/dotfiles/dotx ~
cp ~/git/dotfiles/.Xmodmap ~
cp ~/git/dotfiles/.Xresources ~
cp ~/git/dotfiles/xmonad.hs ~/.xmonad/
cp ~/git/dotfiles/.bash_profile ~
cp ~/git/dotfiles/.xinitrc ~
#cp ~/git/dotfiles/fresh.sh ~
cp ~/git/dotfiles/.xmobarrc ~
#cp ~/git/dotfiles/fun.sh ~
#cp ~/git/dotfiles/urxvtc.sh ~
#cp ~/git/dotfiles/ecx.sh ~
#cp ~/git/dotfiles/gdot.sh ~
cp ~/git/dotfiles/elfeed.org ~/.emacs.d/
cp ~/git/dotfiles/picom.conf ~/.config/picom/picom.conf
cd ~/git/dotfiles/

git status
cd ~
#cp ~/git/dotfiles/
#cp ~/Scripts/* ~/git/dotfiles/
#cd ~/git/dotfiles/
#eval 'ssh-agent -s'
#git commit -a -m "dotfiles update"
#git push
#xrdb ~/.Xresources
#cd ~/git/dwm/dwm/
#git add *
#git commit -a -m "dwm update"
#git push
#cd ~ 
#exec bash
