#! /bin/bash

# read 
# if [[ $a = "bkk" ]]  
# then
# echo "bkkavin $a"
# fi
 #emacs --daemon=bkk
# emacsclient -nc -s "bkk" 
# -F "(quote (name . \"emacsbkkk\"))"

#read $@
#for a in $@
#do
   figlet barrel bharathy
#done 

#
