services:
        mqtt:
                container_name: mosquitto
                image: eclipse-mosquitto
                restart: always
                ports:
                        - "1883:1883"
                        - "9001:9001"
                volumes:
                        - /home/root/mqtt/config:/mosquitto/config
                        - /home/root/mqtt/data:/mosquitto/data
                        - /home/root/mqtt/log:/mosquitto/log
volumes:
        config:
        data:
        log: