services:
        mqtt:
                container_name: mosquitto
                image: eclipse-mosquitto
                restart: always
                ports:
                        - "1883:1883"
                        - "9001:9001"
                volumes:
                        - :/mosquitto/config
                        - :/mosquitto/data
                        - :/mosquitto/log
volumes:
        config:
        data:
        log:
